version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dasa-glances_web_1
      APP_PORT: 61208
      PROXY_AUTH_ADD: "false"

  web:
    image: nicolargo/glances:latest-full
    environment:
      - TZ=Europe/Rome
      - GLANCES_OPT=-w
    pid: host
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
