version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: dasa-openwebui_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/open-webui/open-webui:v0.6.32@sha256:412334cec4b49ed51bfa9a6d28d1fbf3d5622c3ac42f57736e7d5d2bf5f3e94a
    volumes:
      - ${APP_DATA_DIR}/data/open-webui:/app/backend/data
    environment:
      # Exported from ollama app, which is currently a required dependency.
      # This will need to change once optional dependencies are supported.
      OLLAMA_BASE_URL: http://example.com:11434
    restart: on-failure
