version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: dasa-openwebui_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/open-webui/open-webui:v0.6.16@sha256:8738bc96bc503cdda58ec06a6bc14303e1562b3d826ee49742a9b4a4ede63784
    volumes:
      - ${APP_DATA_DIR}/data/open-webui:/app/backend/data
    environment:
      # Exported from ollama app, which is currently a required dependency.
      # This will need to change once optional dependencies are supported.
      OLLAMA_BASE_URL: https://ollama.proserver.cc
    restart: on-failure
