version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dasa-evershop_web_1
      APP_PORT: 3000

  web:
    image: evershop/evershop:2.1.2@sha256:32c5e93ad5b725c27a55d4cdd4c34400b79cc8e82ffb9d9d75edd339eda6eb94
    restart: on-failure
    environment:
      DB_HOST: database
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: postgres
    depends_on:
      - database

  database:
    image: postgres:14.23@sha256:a698d240380a51147281b62c2ad9daff51ae29c781d6d783c0adfd8e48ef4b1e
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
