version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: dasa-cheshire-cat_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  web:
    image: ghcr.io/cheshire-cat-ai/core:1.9.2
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/static:/app/cat/static:rw
      - ${APP_DATA_DIR}/plugins:/app/cat/plugins:rw
      - ${APP_DATA_DIR}/data:/app/cat/data:rw

#Takes a few minutes to start, maybe clear the browser cache after reinstalling
